[build]
    publish = "public"
    functions = "functions"

[dev]
    publish = "public"
    functions = "functions"
    port = 8080
    functionsPort = 52041
	
[[redirects]]
	from = "/*"
	to = "/.netlify/builders/screenshot"
	status = 200
	force = true

# The screenshot function requires an environment variable `AWS_LAMBDA_JS_RUNTIME` to be set to `nodejs12.x` in the Netlify UI
# Read more: https://github.com/11ty/api-screenshot/issues/17